name: modelitWITHpymol-binderized
channels:
  - schrodinger
  - samoturk
  - conda-forge
  - anaconda

dependencies:
  - python
  - pymol>=2.3
  - jupyterlab>=2.0.1
  - pandas
  - matplotlib
  - seaborn
  - libglu
  - glew
  - netpbm
  - pip:
    - .
    - pyfaidx
    - webdriverdownloader
    - selenium
    - ipywidgets
    - jupyter_contrib_nbextensions
    - halo
    - jupytext
    - jupyter-archive

  